### ISSUE TITLE
unnecessary assert when meta server handle a query-meta request

### ISSUE THREAD

**Issue by hycdong** [XiaoMi/rdsn#331]
## Event
Oct 21st, meta server core during recalling table (server version; `1.11.6-release`)
## Coredump and logs
```
#0  0x00007f8e351621d7 in raise () from /lib64/libc.so.6
#1  0x00007f8e351638c8 in abort () from /lib64/libc.so.6
#2  0x00007f8e38ca19fe in dsn_coredump () at /home/wutao1/pegasus-release/rdsn/src/core/core/service_api_c.cpp:76
#3  0x00007f8e384995ba in dsn::replication::server_state::query_configuration_by_index (this=0x25309c0, request=..., response=...) at /home/wutao1/pegasus-release/rdsn/src/dist/replication/meta_server/server_state.cpp:948
#4  0x00007f8e3845d02b in dsn::replication::meta_service::on_query_configuration_by_index (this=0x2414700, msg=0x2b007140) at /home/wutao1/pegasus-release/rdsn/src/dist/replication/meta_server/meta_service.cpp:580
#5  0x00007f8e38cb3cd9 in dsn::task::exec_internal (this=this@entry=0x2b0072d8) at /home/wutao1/pegasus-release/rdsn/src/core/core/task.cpp:180
#6  0x00007f8e38cc7a6d in dsn::task_worker::loop (this=0x21c6dc0) at /home/wutao1/pegasus-release/rdsn/src/core/core/task_worker.cpp:211
#7  0x00007f8e38cc7c39 in dsn::task_worker::run_internal (this=0x21c6dc0) at /home/wutao1/pegasus-release/rdsn/src/core/core/task_worker.cpp:191
#8  0x00007f8e35aba600 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>) at /home/qinzuoyan/git.xiaomi/pegasus/toolchain/objdir/../gcc-4.8.2/libstdc++-v3/src/c++11/thread.cc:84
#9  0x00007f8e3672ddc5 in start_thread () from /lib64/libpthread.so.0
#10 0x00007f8e3522473d in clone () from /lib64/libc.so.6
```
We can't figure out which app leading this coredump because `app` is optimized by complier, and we get timeline from logs:
```
16:01:28.372  drop app (id=5)
16:02:05.968  create app (id=6)
16:26:26.126  drop app (id=6)
16:26:49.700  recall app (id=5)
16:26:49.710  query_configuration_by_index coredump: assertion expression: app->status == app_status::AS_CREATING || app->status == app_status::AS_DROPPING
```
As the logs show, client send query meta request when the requested app status in invalid middle status, as a result, meta server core.

## Solution
function `query_configuration_by_index` (server_state.cpp:948)
```
if (app->status != app_status::AS_AVAILABLE) {
        dassert(app->status == app_status::AS_CREATING || app->status == app_status::AS_DROPPING,
                "invalid status in exist app");
        response.err =
            (app->status == app_status::AS_CREATING ? ERR_BUSY_CREATING : ERR_BUSY_DROPPING);
        return;
    }
```
The `assert` in code above is unnecessary, there is no need to assert when client try to query an app in middle state, so we should remove `assert` and add error log with detailed app information instead.

**Comment by qinzuoyan** [comment]
```As the logs show, client send query meta request when the requested app status is creating or dropping, as a result, meta server core.```

when the requested app status is creating or dropping? not in other status?

**Comment by hycdong** [comment]
It is my mistake, I modify my answer.

**Comment by qinzuoyan** [comment]
sure, your issue is meaningful.
