### ISSUE TITLE
core in replica::update_local_configuration()

### ISSUE THREAD

**Issue by qinzuoyan** [XiaoMi/rdsn#49]
# core背景
时间：2018-05-11 01:52
集群：c3srv-stat
节点：10.142.11.54
版本：1.8.0 (dba2265cf29435729fa6d2a1e4e3e22b71b7d74f) Release
core文件：/home/core/core.replica.replica.98100.1525974558
log文件：/home/work/app/pegasus/c3srv-stat/replica/log/log.495.txt

# core栈信息
```
Core was generated by `/home/work/app/pegasus/c3srv-stat/replica/package/bin/pegasus_server config.ini'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fadb38741d7 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007fadb38741d7 in raise () from /lib64/libc.so.6
#1  0x00007fadb38758c8 in abort () from /lib64/libc.so.6
#2  0x00007fadb685fd8e in dsn_coredump () at /home/work/qinzuoyan/Pegasus/pegasus/rdsn/src/core/core/service_api_c.cpp:176
#3  0x00007fadb67999d0 in dsn::replication::replica::update_local_configuration (this=this@entry=0x7fac401658d0, config=..., same_ballot=same_ballot@entry=true)
    at /home/work/qinzuoyan/Pegasus/pegasus/rdsn/src/dist/replication/lib/replica_config.cpp:738
#4  0x00007fadb67f3d5a in dsn::replication::replica::on_add_learner (this=0x7fac401658d0, request=...) at /home/work/qinzuoyan/Pegasus/pegasus/rdsn/src/dist/replication/lib/replica_learn.cpp:1377
#5  0x00007fadb67687ed in dsn::replication::replica_stub::on_add_learner (this=0x1c36770, request=...) at /home/work/qinzuoyan/Pegasus/pegasus/rdsn/src/dist/replication/lib/replica_stub.cpp:973
#6  0x00007fadb678406d in bool dsn::serverlet<dsn::replication::replica_stub>::register_rpc_handler<dsn::replication::group_check_request>(dsn::task_code, char const*, void (dsn::replication::replica_stub::*)(dsn::replication::group_check_request const&), dsn::gpid)::{lambda(void*, void*)#1}::_FUN(void*, void*) () at /home/work/qinzuoyan/Pegasus/pegasus/rdsn/include/dsn/cpp/serverlet.h:184
#7  0x00007fadb68ba157 in run (req=<optimized out>, this=0x7fac640069b0) at /home/work/qinzuoyan/Pegasus/pegasus/rdsn/include/dsn/tool-api/task.h:249
#8  dsn::rpc_request_task::exec (this=<optimized out>) at /home/work/qinzuoyan/Pegasus/pegasus/rdsn/include/dsn/tool-api/task.h:276
#9  0x00007fadb68b95b9 in dsn::task::exec_internal (this=this@entry=0x7fa253c2ac44) at /home/work/qinzuoyan/Pegasus/pegasus/rdsn/src/core/core/task.cpp:195
#10 0x00007fadb694a8ed in dsn::task_worker::loop (this=0x1ba5b00) at /home/work/qinzuoyan/Pegasus/pegasus/rdsn/src/core/core/task_worker.cpp:323
#11 0x00007fadb694aab9 in dsn::task_worker::run_internal (this=0x1ba5b00) at /home/work/qinzuoyan/Pegasus/pegasus/rdsn/src/core/core/task_worker.cpp:302
#12 0x00007fadb41cc600 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>)
    at /home/qinzuoyan/git.xiaomi/pegasus/toolchain/objdir/../gcc-4.8.2/libstdc++-v3/src/c++11/thread.cc:84
#13 0x00007fadb4a45dc5 in start_thread () from /lib64/libpthread.so.0
#14 0x00007fadb393673d in clone () from /lib64/libc.so.6
(gdb) f 4
#4  0x00007fadb67f3d5a in dsn::replication::replica::on_add_learner (this=0x7fac401658d0, request=...) at /home/work/qinzuoyan/Pegasus/pegasus/rdsn/src/dist/replication/lib/replica_learn.cpp:1377
1377	in /home/work/qinzuoyan/Pegasus/pegasus/rdsn/src/dist/replication/lib/replica_learn.cpp
(gdb) p this._config
$4 = {_vptr.replica_configuration = 0x7fadb6c46570 <vtable for dsn::replication::replica_configuration+16>, pid = {_value = {u = {app_id = 8, partition_index = 5}, value = 21474836488}}, ballot = 27, 
  primary = {_addr = {u = {v4 = {type = 1, padding = 0, port = 43801, ip = 177081397}, uri = {type = 1, uri = 190139702928883712}, group = {type = 1, group = 190139702928883712}, 
        value = 760558811715534849}}}, status = dsn::replication::partition_status::PS_POTENTIAL_SECONDARY, learner_signature = 115964116994, __isset = {pid = true, ballot = true, primary = true, 
    status = true, learner_signature = true}}
```
代码@replica_config.cpp:738：https://github.com/XiaoMi/rdsn/blob/388b88e0daa5026e7b515ba1710f844426c03b4c/src/dist/replication/lib/replica_config.cpp#L738

**Comment by neverchanje** [comment]
fixed by https://github.com/XiaoMi/rdsn/pull/272
